# Generated by Django 4.2.29 on 2026-03-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkypanel', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='framework',
            field=models.CharField(choices=[('none', 'None'), ('wordpress', 'WordPress'), ('laravel', 'Laravel'), ('nodejs', 'Node.js'), ('static', 'Static Template')], default='none', max_length=20),
        ),
    ]
