# Generated by Django 4.2.29 on 2026-03-31 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lkypanel', '0004_website_framework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('disk_limit_mb', models.PositiveIntegerField(default=1024)),
                ('bandwidth_limit_gb', models.PositiveIntegerField(default=10)),
                ('websites_limit', models.PositiveIntegerField(default=1)),
                ('databases_limit', models.PositiveIntegerField(default=1)),
                ('ftp_limit', models.PositiveIntegerField(default=1)),
                ('email_limit', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_reseller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('reseller', 'reseller'), ('user', 'user')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='lkypanel.package'),
        ),
    ]
