# Generated by Django 4.2.29 on 2026-03-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkypanel', '0005_package_user_is_2fa_enabled_user_otp_secret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
