[lky-admin]
enabled = True
port = 2087
filter = lkypanel
logpath = /var/log/lkypanel/admin-error.log
maxretry = 3
findtime = 600
bantime = 3600

[lky-user]
enabled = True
port = 2083
filter = lkypanel
logpath = /var/log/lkypanel/user-error.log
maxretry = 3
findtime = 600
bantime = 3600
