# Generated by Django 4.2.29 on 2026-04-02 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lkypanel', '0007_cronjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_path', models.CharField(max_length=1000)),
                ('trash_name', models.CharField(max_length=255)),
                ('trashed_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trash_items', to='lkypanel.website')),
            ],
            options={
                'ordering': ['-trashed_at'],
            },
        ),
    ]
